---
version: "3.7"

services:
  angular:
    command: ng serve --host 0.0.0.0
    container_name: angular
    image: ${APP}-angular:${APP_VERSION}
    ports:
      - 8883:4200
    volumes:
      - ./services/${APP}-angular:/srv/${APP}-angular

  elm:
    command: elm-app start
    container_name: elm
    image: ${APP}-elm:${APP_VERSION}
    ports:
      - 8882:3000
    volumes:
      - ./services/${APP}-elm:/srv/${APP}-elm

  ember:
    command: ember serve
    container_name: ember
    image: ${APP}-ember:${APP_VERSION}
    ports:
      - 8881:4200
    volumes:
      - ./services/${APP}-ember:/srv/${APP}-ember

  react:
    command: npm start
    container_name: react
    image: ${APP}-react:${APP_VERSION}
    ports:
      - 8888:3000
    volumes:
      - ./services/${APP}-react:/srv/${APP}-react

  vue:
    command: yarn serve
    container_name: vue
    image: ${APP}-vue:${APP_VERSION}
    ports:
      - 8880:8080
    volumes:
      - ./services/${APP}-vue:/srv/${APP}-vue
