---
version: "3.7"

services:
  react:
    command: npm start
    container_name: react
    image: ${APP}-react:${APP_VERSION}
    ports:
      - 8888:3000
    volumes:
      - ./services/${APP}-react:/srv/${APP}-react

  vue:
    command: yarn serve
    container_name: vue
    image: ${APP}-vue:${APP_VERSION}
    ports:
      - 8880:8080
    volumes:
      - ./services/${APP}-vue:/srv/${APP}-vue
